name: CI
on: [push, pull_request]
env:
  OPENRCT2_BUILD_SERVER: GitHub
  OPENRCT2_ORG_TOKEN: ${{ secrets.OPENRCT2_ORG_TOKEN }}
  BACKTRACE_IO_TOKEN: ${{ secrets.BACKTRACE_IO_TOKEN }}
  OPENRCT2_VERSION: 0.1.2
jobs:
  windows-mingw-nt51:
    name: Windows (win32, WinNT5.1) using mingw
    runs-on: ubuntu-latest
    container:
      image: openrct2/openrct2-build:0.2.4-mingw
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build OpenRCT2
        run: |
          sudo su
          mkdir bin && cd bin
          cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=../CMakeLists_mingw.txt -DCMAKE_BUILD_TYPE=MinSizeRel -DDISABLE_IPO=on -DDISABLE_NETWORK=ON -DDISABLE_HTTP=ON -DDISABLE_HTTP_TWITCH=on -DDISABLE_TTF=On -DFORCE32=on -DENABLE_SCRIPTING=Off -DCMAKE_CXX_FLAGS="-Wno-error=unused-function -DZIP_STATIC=1 -static -static-libgcc -static-libstdc++ -Bdynamic" -DSTATIC=on -DMINGW_TARGET_NT5_1=ON -DPORTABLE=ON
          ninja -k0
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v2-preview
        with:
          name: "OpenRCT2-NT5.1"
          path: bin/openrct2.exe
